/* oxlint-disable no-danger -- HTML is generated by Shiki from controlled code strings in this component. */
'use client';

import * as React from 'react';
import { codeToHtml } from 'shiki';

import { CopyButton } from '@/components/copy-button';
import { cn } from '@/lib/utils';

const highlightedHtmlCache = new Map<string, Promise<string>>();

function escapeHtml(value: string): string {
  return value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;');
}

async function getHighlightedHtml(code: string, language: string): Promise<string> {
  const cacheKey = `${language}\u0000${code}`;
  const cached = highlightedHtmlCache.get(cacheKey);
  if (cached) {
    return cached;
  }

  const task = codeToHtml(code, {
    lang: language,
    themes: {
      light: 'github-light-default',
      dark: 'github-dark-high-contrast',
    },
    defaultColor: false,
  });

  highlightedHtmlCache.set(cacheKey, task);

  try {
    return await task;
  } catch (error) {
    highlightedHtmlCache.delete(cacheKey);
    throw error;
  }
}

interface CodeBlockProps {
  code: string;
  label?: string;
  language: string;
  className?: string;
  codeContainerClassName?: string;
}

export function CodeBlock({ code, label, language, className, codeContainerClassName }: CodeBlockProps) {
  const [html, setHtml] = React.useState<string | null>(null);
  const fallbackHtml = React.useMemo(() => `<pre><code>${escapeHtml(code)}</code></pre>`, [code]);

  React.useEffect(() => {
    let active = true;
    getHighlightedHtml(code, language)
      .then((nextHtml) => {
        if (active) setHtml(nextHtml);
      })
      .catch(() => {
        if (active) setHtml(null);
      });

    return () => {
      active = false;
    };
  }, [code, language]);

  return (
    <div className={cn('flex flex-col gap-1', className)}>
      {label && <span className='text-[11px] font-medium tracking-wider text-muted-foreground uppercase'>{label}</span>}
      <div className='relative overflow-hidden rounded-lg border bg-card'>
        <CopyButton
          label={(label && `${label} code`) || 'code'}
          value={code}
          size='icon-xs'
          className='absolute top-2 right-2 z-10'
        />
        <div
          className={cn(
            'overflow-auto text-xs leading-relaxed [&_code]:font-mono [&_pre]:m-0 [&_pre]:min-w-full [&_pre]:p-3 [&_pre]:pr-10 [&_pre]:font-mono [&_span]:font-mono',
            codeContainerClassName,
          )}
          dangerouslySetInnerHTML={{ __html: html ?? fallbackHtml }}
        />
      </div>
    </div>
  );
}
